version: "3.7"
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: avanmall
    user: '1000:1000'
    container_name: avanmall-app
    restart: unless-stopped
    working_dir: /avanmall
    volumes:
      - ./src:/avanmall
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - avanmall

  db:
    image: mysql:5.7
    container_name: avanmall-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: avanmall
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/log/mysql:/var/log/mysql
    networks:
      - avanmall

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - avanmall

  nginx:
    image: nginx:alpine
    container_name: avanmall-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./src:/avanmall
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/log/nginx:/var/log/nginx
    networks:
      - avanmall
  # redis:
  #   image: redis:latest
  #   container_name: avanmall-redis
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - avanmall

  # mailhog:
  #   image: mailhog/mailhog
  #   logging:
  #     driver: 'none'
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   networks:
  #     - avanmall 

networks:
  avanmall:
    driver: bridge